<a href="https://colab.research.google.com/github/raamiiChu/111-1_NCCU_DCT_3D_Game_Programming_G2/blob/main/%E6%B8%AC%E8%A9%A6%E7%94%A8/%E8%BC%B8%E5%87%BAexcel(%E6%AA%A2%E8%A6%96%E8%B3%87%E6%96%99%E6%95%B8%E9%87%8F).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json

資料來源：https://huggingface.co/datasets/common_voice/blob/main/dataset_infos.json

In [ ]:
with open("dataset_infos.json", "r", encoding="utf-8") as file:
    data = json.load(file)

In [ ]:
# 獲取詳細數量
result =  {lang : 
           {split : data[lang]["splits"][split]["num_examples"] for split in data[lang]["splits"].keys()} 
           for lang in data.keys()}

In [ ]:
result["ab"]

{'invalidated': 8,
 'other': 752,
 'test': 9,
 'train': 22,
 'validated': 31,
 'validation': 0}

In [ ]:
df = pd.DataFrame(result)

# 輸出成 excel
df.T.to_excel("各語言資料詳細數量.xlsx")

In [ ]:
df.T

              train   test  validation   other  validated  invalidated
ab               22      9           0     752         31            8
ar            14227   7622        7517   18283      43291         6333
as              270    110         124       0        504           31
br             2780   2087        1997   10912       8560          623
ca           285584  15724       15724   64446     416701        18846
cnh             807    752         756    2934       2432          433
cs             5655   4144        4118    7475      30431          685
cv              931    788         818    6927       3496         1282
cy             6839   4820        4776   17919      72984         3648
de           246525  15588       15588   10095     565186        32789
dv             2680   2202        2077       0      11866          840
el             2316   1522        1401    5659       5996          185
en           564337  16164       16164  169895    1224864       189562
eo            19587   8969        8987    2946      58094         4736
es           161813  15089       15089  144791     236314        40640
et             2966   2509        2507     569      10683         3557
eu             7505   5172        5172   23570      63009         5387
fa             7593   5213        5213   22510     251659        11698
fi              460    428         415     149       1305           59
fr           298982  15763       15763    3222     461004        40351
fy-NL          3927   3020        2790   21569      10495         1031
ga-IE           541    506         497    2130       3352          409
hi              157    127         135     139        419           60
hsb             808    387         172      62       1367          227
hu             3348   1649        1434     295       6457          169
ia             3477    899        1601    1095       5978          192
id             2130   1844        1835    6782       8696          470
it            58015  12928       12928   14549     102579        12189
ja              722    632         586     885       3072          504
ka             1058    656         527      44       2275          139
kab          120530  14622       14622   88021     573718        18134
ky             1955   1503        1511    7223       9236          926
lg             1250    584         384    3110       2220          290
lt              931    466         244    1629       1644          102
lv             2552   1882        2002    1560       6444          143
mn             2183   1862        1837    3272       7487          667
mt             2036   1617        1516    5714       5747          314
nl             9460   5708        4938      27      52488         3308
or              388     98         129    4302        615           62
pa-IN           211    116          44    1411        371           43
pl             7468   5153        5153   12848      90791         4601
pt             6514   4641        4592    8390      41584         1740
rm-sursilv     1384   1194        1205    2102       3783          639
rm-vallader     574    378         357     727       1316          374
ro             3399   1778         858    1945       6039          485
ru            15481   8007        7963   10247      74256         3056
rw           515197  15724       15032   22923     832929       206790
sah            1442    757         405    1275       2606           66
sl             2038    881         556    2502       4669           92
sv-SE          2331   2027        2019    3043      12552          462
ta             2009   1781        1779    7428      12652          594
th             2917   2188        1922    2671       7028          467
tr             1831   1647        1647     325      18685         1726
tt            11211   4485        2127    1798      25781          287
uk             4035   3235        3236    8161      22337         1255
vi              221    198         200     870        619           78
vot               3      0           0     411          3            6
zh-CN         18541   8760        8743    8948      36405         5305
zh-HK          7506   5172        5172   38830      41835         2999
zh-TW          3507   2895        2895   22477      61232         3584